const fs = require('node:fs');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const legacy=require('./legacy.json');
const C=require('./components.cjs');
const {escape:e,arrow,play,external,whatsapp,workCard:card,heading,cta}=C;
const root=path.resolve(__dirname,'..');
const projects=require('../assets/projects.json');
const site=require('./site.json');
const googleReviews=require('./reviews.json');
const collections=require('./collections.json');
const featured=site.featuredProjects.map(id=>projects.find(p=>p.id===id)).filter(Boolean);
const sortedProjects=[...featured,...projects.filter(p=>!site.featuredProjects.includes(p.id)).sort((a,b)=>a.order-b.order)];
const homeData=legacy.pages['index.html'];
const byId=id=>projects.find(p=>p.id===id);
const routes=[];
const version='20261003-media1';
const schema=(type,props)=>({'@context':'https://schema.org','@type':type,...props});
function page(file,body,{title,description,jsonld=[],active='',bodyClass='',image='/bg-poster-desktop.jpg',home=false}={}) {
  const old=legacy.pages[file];
  title=title||old?.title||'Take Cut | Faça valer o play.';
  description=description||old?.description||'Produção, edição e inteligência artificial para marcas que querem ser assistidas.';
  const route=file==='index.html'?'/':file.endsWith('/index.html')?'/'+file.slice(0,-10):'/'+file;
  const canonical=old?.canonical||'https://www.takecut.com.br'+route;
  routes.push(canonical);
  if(!jsonld.length&&old)jsonld=old.jsonld;
  const analytics=home?`<script src="/assets/analytics.js?v=${version}"></script><script async src="https://www.googletagmanager.com/gtag/js?id=AW-17039172373"></script>`:'';
  const html=`<!DOCTYPE html>
<html lang="pt-BR"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${e(title)}</title><meta name="description" content="${e(description)}"><meta name="theme-color" content="#0B0B0C"><meta name="robots" content="index,follow">
<link rel="canonical" href="${e(canonical)}"><link rel="icon" href="/favicon-takecut.png"><link rel="apple-touch-icon" href="/favicon-takecut.png">
<meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="Take Cut"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="https://www.takecut.com.br${image}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${e(title)}"><meta name="twitter:description" content="${e(description)}"><meta name="twitter:image" content="https://www.takecut.com.br${image}">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/studio.css?v=${version}">${home?`<link rel="preload" as="image" href="${site.hero.desktopPoster}" media="(min-width: 701px)"><link rel="preload" as="image" href="${site.hero.mobilePoster}" media="(max-width: 700px)">`:''}
${jsonld.map(data=>`<script type="application/ld+json">${JSON.stringify(data).replaceAll('<','\\u003c')}</script>`).join('\n')}${analytics}</head>
<body class="${bodyClass}">${C.atmosphere()}${C.header(active)}<main id="main">${body}</main>${C.footer()}${C.viewer()}<script src="/assets/studio.js?v=${version}" defer></script><script src="/cookie-consent.js?v=${version}" defer></script></body></html>\n`;
  fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),html);
}

const processItems=[
  ['Estratégia','Antes do primeiro frame, uma pergunta: o que esse vídeo precisa provocar? Objetivo, público e direção no mesmo corte.','criativo-trafego-pago-3d'],
  ['Roteiro','Uma ideia clara. Um gancho que funciona. Uma história que sabe aonde quer chegar.','youtube-narrativo'],
  ['Captação','Luz, enquadramento e intenção. A produção começa muito antes de apertar REC.','hospedagem-tematica'],
  ['Edição','Escolher o que fica. Tirar o que sobra. Encontrar o ritmo que faz você continuar assistindo.','tratamento-audiovisual'],
  ['Sound design','O detalhe que você talvez não perceba, mas sente. Som que dá peso, textura e movimento à imagem.','video-emocional'],
  ['Inteligência artificial','Para quando a ideia vai além da câmera. IA com direção, contexto e acabamento.','ia-marca']
];
const processSection=`<section id="how-it-works" class="craft-section shell section-space"><span id="bastidores" class="anchor-alias"></span>${heading('O que a gente faz','A gente não<br>só corta vídeo.','Da primeira ideia ao último frame.<br>Cada decisão tem uma intenção.','02 / PROCESSO')}<div class="craft-layout"><div class="craft-visual" aria-hidden="true"><img src="${byId('criativo-trafego-pago-3d').thumbnail}" alt="" width="1080" height="1920"><span class="mono">TAKE CUT / PROCESSO CRIATIVO</span></div><div class="craft-list">${processItems.map(([title,text,id],i)=>`<details class="craft-item"${i===0?' open':''} data-process-image="${byId(id).thumbnail}"><summary><span class="mono">0${i+1}</span><h3>${title}</h3><span class="plus" aria-hidden="true"></span></summary><div class="craft-answer"><p>${text}</p><img class="craft-mobile-image" src="${byId(id).thumbnailSmall}" alt="Frame de ${e(byId(id).title)}" loading="lazy" width="${byId(id).width}" height="${byId(id).height}"></div></details>`).join('')}</div></div></section>`;

const collectionLinks=`<div class="collection-links">${collections.map(collection=>{const items=projects.filter(p=>p.category.includes(collection.category));const cover=items.find(p=>p.id===collection.cover)||items[0];return `<a class="collection-link" href="/portfolio/colecoes/${e(collection.slug)}/"><img src="${cover.thumbnailSmall}" alt="" width="${cover.width}" height="${cover.height}" loading="lazy"><div><p class="eyebrow">Coleção / ${items.length} projetos</p><h3>${e(collection.title)}</h3><p>${e(collection.summary)}</p></div><span class="collection-arrow">${arrow}</span></a>`;}).join('')}</div>`;
const hero=`<section class="hero" id="home"><div class="hero-film" aria-hidden="true"><picture><source srcset="${site.hero.mobilePoster}" media="(max-width:700px)"><img src="${site.hero.desktopPoster}" alt="" width="1920" height="1080" fetchpriority="high"></picture><video id="heroVideo" data-desktop="${site.hero.desktopVideo}" data-mobile="${site.hero.mobileVideo}" muted autoplay loop playsinline preload="none" disablepictureinpicture tabindex="-1"></video></div><div class="hero-content shell"><p class="eyebrow hero-kicker">Produtora audiovisual / São Paulo · Brasil</p><h1>Faça valer<br>o <span>play.</span></h1><div class="hero-bottom"><p>Produção, edição e inteligência artificial<br>para marcas que querem ser assistidas.</p><div class="hero-actions"><a href="#work" class="button button-accent">Ver nossos trabalhos ${play}</a>${external(whatsapp(),'Começar um projeto','text-link')}</div></div></div><div class="hero-foot shell"><a href="#work" class="mono scroll-cue">SCROLL PARA DESCOBRIR</a><span class="mono hero-coordinate">PRODUÇÃO / PÓS / IA</span><button class="motion-toggle hero-motion" type="button" aria-pressed="false">Pausar animações</button></div></section>`;
const selected=`<section id="work" class="selected-section shell section-space"><span id="portfolio" class="anchor-alias"></span>${heading('Selected work / Seleção Take Cut','Projetos<br>em destaque.','Uma amostra do que acontece<br>quando a ideia encontra o corte.','01 / SELEÇÃO')}<div class="selected-lead" data-reveal>${card(featured.find(p=>p.orientation==='horizontal'))}<p class="editorial-note">Uma ideia. Outro universo.<span>Direção criativa + inteligência artificial.</span></p></div><div class="vertical-reel-row" aria-label="Trabalhos verticais — deslize para explorar">${featured.filter(p=>p.orientation==='vertical').slice(0,3).map(p=>card(p,{compact:true})).join('')}</div><div class="selected-wide" data-reveal>${card(featured.filter(p=>p.orientation==='horizontal')[1] || featured.at(-1))}</div>${collectionLinks}<a class="text-link all-work" href="/portfolio/">Explorar todos os trabalhos ${arrow}</a></section>`;
const cutIds=site.cutRoomProjects;
const cut=`<section class="cut-section section-space" id="cut-room"><div class="shell">${heading('Dentro do processo','CUT ROOM<span class="accent">.</span>','Fragmentos, experimentos e cortes.<br>Uma janela para o nosso universo.','03 / EXPERIMENTOS')}<div class="cut-grid">${cutIds.map((id,i)=>`<div class="cut-cell cut-${i}"><p class="mono">0${i+1} / ${['AI','COMMERCIAL','SOCIAL','FILM','MOTION'][i]}</p>${card(byId(id),{compact:true})}</div>`).join('')}</div><div class="cut-ruler" aria-hidden="true"><span>00:00:00:00</span><span>IN</span><span>OUT</span><span>TAKE / CUT</span></div></div></section>`;
const caseSection=`<section class="cases-section shell section-space" id="cases">${heading('Quando o play vira resultado','Além do frame.','Projetos com resultado.<br>Não promessas de algoritmo.','04 / CASES')}<div class="case-grid">${[{id:'institucional-vertical',number:'522',text:'Apresentar a experiência de uma hospedagem.',process:'Narrativa visual, ritmo e edição para redes sociais.'},{id:'conteudo-social',number:'255',text:'Gerar atenção rápida para uma campanha.',process:'Gancho inicial, cortes, legendas e mensagem direta.'}].map(item=>`<article class="case-study"><div class="case-number">${item.number}<span>K+</span></div><p class="eyebrow">Visualizações</p>${card(byId(item.id),{compact:true})}<dl><div><dt>Objetivo</dt><dd>${item.text}</dd></div><div><dt>Take Cut</dt><dd>${item.process}</dd></div></dl></article>`).join('')}</div><p class="fine-print">Resultados de projetos já realizados. O desempenho varia conforme conteúdo, público e distribuição.</p></section>`;
const services=`<section class="services-section shell section-space" id="services">${heading('Do zero ao último frame','Uma ideia.<br>Muitas possibilidades.','','05 / SERVIÇOS')}<div class="service-list"><article><span class="mono">01 / PRODUÇÃO</span><h3>Da ideia<br>à gravação.</h3><p>Roteiro, direção e captação.<br>A base de uma história bem contada.</p>${external(whatsapp('Olá, quero conversar sobre produção e gravação de um vídeo.'),'Vamos produzir','text-link')}</article><article><span class="mono">02 / PÓS-PRODUÇÃO</span><h3>O bruto<br>vira narrativa.</h3><p>Edição, motion, cor e som.<br>É aqui que cada frame encontra seu lugar.</p><a href="/edicao-de-reels/" class="text-link">Encontrar meu corte ${arrow}</a></article><article><span class="mono">03 / INTELIGÊNCIA ARTIFICIAL</span><h3>Além do<br>possível.</h3><p>Cenas generativas, VFX e direção de arte.<br>Tecnologia a serviço da ideia. Não o contrário.</p><a href="/videos-com-ia/" class="text-link">Explorar com IA ${arrow}</a></article></div></section>`;
const clients=`<section class="clients-section shell section-space">${heading('Boas companhias','Algumas marcas que já<br>deram play com a gente.')}<div class="client-logos">${homeData.clients.map(c=>`<a href="${e(c.url)}" target="_blank" rel="noopener"><img src="/assets/images/${path.parse(c.image).name}.webp" alt="${e(c.alt)}" loading="lazy" width="160" height="88"></a>`).join('')}</div></section>`;
const reviews=`<section class="reviews-section shell section-space" aria-label="Avaliações de clientes"><p class="eyebrow">Do outro lado da entrega / ${googleReviews.items.length} avaliações no Google</p><div class="reviews-stage" aria-live="polite">${googleReviews.items.map((r,i)=>`<figure class="review-slide"${i?' hidden':''}><blockquote>“${e(r.quote)}”</blockquote><figcaption><span class="review-rating" aria-label="${r.rating} de 5 estrelas">${C.star.repeat(r.rating)}</span><strong>${e(r.name.trim().split(/\s+/)[0])}</strong><small>Trecho de avaliação no Google. <a href="${e(googleReviews.sourceUrl)}" target="_blank" rel="noopener">Ler avaliações completas</a></small></figcaption></figure>`).join('')}</div><div class="review-controls"><button type="button" class="icon-button" data-review-step="-1" aria-label="Avaliação anterior">${C.chevronLeft}</button><span id="reviewPosition" class="mono">01 / ${String(googleReviews.items.length).padStart(2,'0')}</span><button type="button" class="icon-button" data-review-step="1" aria-label="Próxima avaliação">${C.chevronRight}</button></div></section>`;
const homeGraph=structuredClone(homeData.jsonld[0]);homeGraph['@graph']=homeGraph['@graph'].filter(n=>n['@type']!=='FAQPage');
page('index.html',hero+selected+processSection+cut+caseSection+services+clients+reviews+cta(),{home:true,bodyClass:'home-page',jsonld:[homeGraph]});

const objectives=[['all','Todos os trabalhos'],['vender','Quero vender'],['impressionar','Quero impressionar'],['explicar','Quero explicar'],['emocionar','Quero emocionar'],['atencao','Quero prender atenção']];
const categories=['Todos','IA',...collections.map(c=>c.category),'Produto','Automotive','Social','Turismo','YouTube','Institucional','Publicidade'];
const portfolio=`<section class="page-intro shell"><p class="eyebrow">Portfólio Take Cut / ${projects.length} projetos</p><h1>O que você<br>quer <span class="accent">assistir?</span></h1><div class="intro-bottom"><p>Ideias diferentes pedem vídeos diferentes.<br>Encontre o seu próximo ponto de partida.</p><span class="mono">ESCOLHA A INTENÇÃO. DÊ O PLAY.</span></div></section><section class="portfolio-section shell" aria-label="Projetos do portfólio">${collectionLinks}<div class="portfolio-filters" id="portfolioFilters"><div class="objective-filters" role="group" aria-label="Filtrar por objetivo">${objectives.map(([id,label])=>`<button type="button" data-objective-filter="${id}" aria-pressed="${id==='all'}">${label}</button>`).join('')}</div><div class="category-filters" role="group" aria-label="Filtrar por categoria">${categories.map((c,i)=>`<button type="button" data-category-filter="${i?c:'all'}" aria-pressed="${!i}">${c}</button>`).join('')}</div></div><div class="selection-label"><p class="eyebrow">Seleção atual</p><p id="resultCount" class="mono" aria-live="polite">${projects.length} projetos</p></div><div class="portfolio-grid" id="projectGrid">${sortedProjects.map(p=>card(p)).join('')}</div><div class="empty-state" id="emptyState" hidden><h2>A próxima ideia pode ser sua.</h2><p>Ainda não temos um projeto nessa combinação. Explore outra seleção ou converse com a gente.</p><button type="button" class="button" data-reset-filters>Ver todos os trabalhos ${arrow}</button></div><div class="load-more-wrap"><button type="button" class="button" id="loadMore" hidden>Mais trabalhos ${arrow}</button></div><noscript><p>Todos os projetos estão disponíveis abaixo. Abra um projeto para assistir ao vídeo.</p></noscript></section>${cta()}`;
page('portfolio/index.html',portfolio,{active:'work',bodyClass:'portfolio-page',jsonld:[schema('CollectionPage',{name:'Portfólio Take Cut',url:'https://www.takecut.com.br/portfolio/',mainEntity:schema('ItemList',{itemListElement:projects.map((p,i)=>({'@type':'ListItem',position:i+1,url:'https://www.takecut.com.br/portfolio/'+p.slug+'/'}))})})]});

for(const collection of collections){
  const items=projects.filter(p=>p.category.includes(collection.category));
  page('portfolio/colecoes/'+collection.slug+'/index.html',`<section class="page-intro shell"><a class="back-link mono" href="/portfolio/">${C.chevronLeft} TODOS OS TRABALHOS</a><p class="eyebrow">Coleção Take Cut / ${items.length} projetos</p><h1>${e(collection.title)}</h1><p>${e(collection.description)}</p></section><section class="portfolio-section shell" aria-label="${e(collection.title)}"><div class="portfolio-grid">${items.map(p=>card(p)).join('')}</div></section>${cta()}`,{active:'work',bodyClass:'portfolio-page collection-page',title:collection.title+' | Take Cut',description:collection.description,jsonld:[schema('CollectionPage',{name:collection.title,url:'https://www.takecut.com.br/portfolio/colecoes/'+collection.slug+'/',mainEntity:schema('ItemList',{itemListElement:items.map((p,i)=>({'@type':'ListItem',position:i+1,url:'https://www.takecut.com.br/portfolio/'+p.slug+'/'}))})})]});
}

const faq=homeData.jsonld[0]['@graph'].find(n=>n['@type']==='FAQPage');
const faqHtml=`<section class="faq-section section-space" id="plan-faq">${heading('Antes do primeiro play','Vamos tirar<br>as dúvidas.')}<div class="faq-list">${faq.mainEntity.map(q=>`<details><summary>${e(q.name)}<span class="plus" aria-hidden="true"></span></summary><p>${e(q.acceptedAnswer.text)}</p></details>`).join('')}</div></section>`;
page('planos/index.html',`<div class="shell"><section class="page-intro"><p class="eyebrow">Planos / Formatos de contratação</p><h1>Um começo<br>para cada <span class="accent">ideia.</span></h1><p>Do primeiro teste à produção completa.<br>Escolha o ponto de partida. A gente cuida do corte.</p></section><div class="plans-grid">${homeData.plans.join('')}</div><p class="fine-print">Valores sugeridos, sujeitos ao escopo. Deslocamento, locação, elenco, mídia paga e demandas fora do escopo são orçados separadamente.</p>${faqHtml}</div>${cta()}`,{title:'Planos de produção e edição de vídeo | Take Cut',description:'Conheça os planos Teste de venda, Campanha essencial e Produção completa da Take Cut. Entregas, preços e perguntas frequentes.',jsonld:[{...faq,'@id':'https://www.takecut.com.br/planos/#plan-faq'}]});

const about=`<section class="page-intro shell"><p class="eyebrow">Por trás do corte</p><h1>Gente que pensa<br>em <span class="accent">movimento.</span></h1><div class="intro-bottom"><p>Somos a Take Cut.<br>Uma boa ideia não nasceu para passar despercebida.</p><span class="mono">SÃO PAULO / BRASIL</span></div></section><section class="about-story shell"><div class="about-frame">${card(byId('tratamento-audiovisual'))}</div><div class="about-copy"><p class="eyebrow">O nosso jeito</p><h2>Mais intenção.<br>Menos vídeo por vídeo.</h2><p>Bons negócios merecem ser vistos. A Take Cut existe para transformar ideias, produtos e histórias em vídeos com ritmo, clareza e personalidade.</p><p>A gente escuta antes de editar. Entende o que precisa ser dito, encontra o gancho e trabalha cada detalhe — da primeira imagem ao último som.</p><p>Tecnologia abre possibilidades. Direção dá sentido a elas. É assim que pensamos a produção, a pós e o uso de inteligência artificial.</p><div class="techniques"><span>DaVinci Resolve</span><span>Blender 3D</span><span>IA + direção criativa</span></div></div></section>${processSection}<section class="shell about-values section-space">${heading('O que fica depois do corte','Clareza. Cuidado.<br>Vontade de ir além.','Respeito a quem confia seu projeto à gente.<br>Compromisso com cada entrega.')}<a href="/portfolio/" class="text-link">Conheça nosso trabalho ${arrow}</a></section>${cta()}`;
page('sobre/index.html',about,{active:'about',title:'Sobre a Take Cut | Audiovisual com intenção',description:'Conheça a Take Cut: nosso jeito de pensar, produzir e editar vídeos com estratégia, criatividade e tecnologia.'});

const gearNotes={cameras:'Para construir a imagem: escolha a câmera a partir do tipo de produção, das lentes e do fluxo de trabalho.',iluminacao:'Para desenhar a luz: controle, direção e suavidade fazem parte da linguagem do vídeo.',audio:'Para dar clareza à mensagem: pense na voz, no ambiente e na distância de captação.',acessorios:'Para cuidar do processo: estabilidade, organização e proteção também entram no set.'};
const gearLabels={cameras:'Câmeras',iluminacao:'Iluminação',audio:'Áudio',acessorios:'Acessórios'};
const gear=`<section class="page-intro shell"><p class="eyebrow">O que entra em cena</p><h1>TAKE CUT<br><span class="accent">GEAR.</span></h1><div class="intro-bottom"><p>Uma seleção para montar o seu setup.<br>Câmeras, luz, áudio e os detalhes que fazem diferença.</p><span class="mono">CURADORIA / EQUIPAMENTOS</span></div></section><section class="gear-section shell"><div class="gear-toolbar"><label class="gear-search" for="searchInput"><span class="eyebrow">O que você procura?</span><input type="search" id="searchInput" placeholder="Buscar equipamento" autocomplete="off"></label><fieldset class="gear-filters"><legend class="eyebrow">Categoria</legend>${Object.entries(gearLabels).map(([id,label])=>`<label><input type="checkbox" value="${id}">${label}</label>`).join('')}</fieldset><span id="gearCount" class="mono" aria-live="polite">10 equipamentos</span></div><div class="gear-grid">${legacy.pages['produtos/index.html'].items.map((item,i)=>`<article class="gear-item" data-gear-category="${item.category}" data-gear-name="${e(item.search+' '+item.title)}"><div class="gear-image"><span class="mono">${String(i+1).padStart(2,'0')} / GEAR</span><img src="/assets/images/${path.parse(item.image).name}.webp" width="800" height="600" alt="${e(item.alt)}" loading="lazy"></div><div class="gear-info"><p class="eyebrow">${gearLabels[item.category]}</p><h2>${e(item.title)}</h2><p>${gearNotes[item.category]}</p><p class="gear-price">${e(item.price)}</p><div class="gear-actions">${external(item.buy,'Ver equipamento','text-link')}${item.rent?external(item.rent,'Consultar locação','text-link'):''}</div></div></article>`).join('')}</div><p class="empty-state" id="gearEmpty" hidden>Nenhum equipamento encontrado. Experimente outro termo ou categoria.</p><p class="fine-print">Os links de compra levam a lojas externas e podem ser links de afiliado. Confirme especificações, disponibilidade e preço no vendedor. Valores de locação a confirmar pelo WhatsApp.</p></section>`;
page('produtos/index.html',gear,{title:'Take Cut Gear | Equipamentos para produção audiovisual',description:'Seleção de câmeras, iluminação, áudio e acessórios para produções. Explore equipamentos e consulte opções de locação.'});

for(const [file,data] of Object.entries(legacy.pages)){
  if(['index.html','portfolio/index.html','produtos/index.html'].includes(file))continue;
  if(file==='termos.html'){page(file,`<section class="legal-page shell">${data.content}</section>`);continue;}
  const pick=file.includes('pousadas')?'hospedagem-tematica':file.includes('ia/')?'possibilidades-com-ia':file.includes('reels')?'reels-esmalteria':file.includes('trafego')?'criativo-trafego-pago-3d':'anuncio-produto';
  page(file,`<div class="niche-page shell">${data.content}<section class="niche-project section-space">${heading('Na prática',pick==='possibilidades-com-ia'?'Uma ideia.<br>Várias possibilidades.':'Veja a linguagem<br>em movimento.')}<div class="niche-feature">${card(byId(pick))}</div><a href="/portfolio/" class="text-link">Explorar outros trabalhos ${arrow}</a></section></div>`,{active:'services'});
}

for(const p of projects){
  const related=projects.filter(q=>q.id!==p.id&&q.category.some(c=>p.category.includes(c))).slice(0,3);
  const body=`<section class="project-intro shell"><a class="back-link mono" href="/portfolio/">${C.chevronLeft} TODOS OS TRABALHOS</a><p class="eyebrow">${e(p.category.join(' / '))}</p><h1>${e(p.title)}</h1><p>${e(p.shortTitle)}</p></section><section class="project-film shell ${p.orientation}"><video controls playsinline preload="none" poster="${e(p.thumbnail)}" width="${p.width}" height="${p.height}" aria-label="${e(p.title)}"><source src="${e(p.fullVideo)}" type="video/mp4">Seu navegador não suporta vídeo. <a href="${e(p.fullVideo)}">Abrir o arquivo</a></video></section><section class="project-context shell section-space"><div><p class="eyebrow">Contexto</p><h2>Uma intenção<br>em cada frame.</h2><p>${e(p.description)}</p></div><div><p class="eyebrow">Processo / Técnicas</p><div class="techniques">${p.techniques.map(t=>`<span>${e(t)}</span>`).join('')}</div><p class="fine-print">Formato ${p.orientation==='horizontal'?'horizontal':p.orientation==='square'?'quadrado':'vertical'}. ${p.client?'Cliente: '+e(p.client):''}${p.year?' / '+p.year:''}</p>${external(whatsapp('Olá, vi o projeto '+p.title+' no portfólio da Take Cut e quero criar algo nessa direção.'),'Quero algo nessa direção','button button-accent')}</div></section><section class="shell section-space">${heading('Continue assistindo','Outros cortes.')}<div class="related-grid">${related.map(q=>card(q,{compact:true})).join('')}</div></section>${cta()}`;
  page('portfolio/'+p.slug+'/index.html',body,{active:'work',title:p.title+' | Portfólio Take Cut',description:p.description,image:p.thumbnail,jsonld:[schema('CreativeWork',{name:p.title,description:p.description,url:'https://www.takecut.com.br/portfolio/'+p.slug+'/',thumbnailUrl:'https://www.takecut.com.br'+p.thumbnail,creator:{'@type':'Organization',name:'Take Cut'},inLanguage:'pt-BR'})]});
}
fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+routes.map(url=>'  <url><loc>'+e(url)+'</loc></url>').join('\n')+'\n</urlset>\n');
// Include generated, not-yet-staged pages when refreshing CSP, without weakening validation.
execFileSync(process.execPath,[path.join(root,'_security/check.cjs'),'--write'],{cwd:root,stdio:'inherit'});
console.log('Built '+routes.length+' static pages from '+projects.length+' projects.');
