const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const arrow = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M12 5l7 7-7 7"/></svg>';
const play = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 11 7-11 7Z"/></svg>';
const close = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>';
const whatsapp = (message='Olá, conheci a Take Cut e quero conversar sobre um projeto de vídeo.') => 'https://wa.me/551153044748?text='+encodeURIComponent(message);
const external = (url,label,classes='text-link') => `<a class="${classes}" href="${escape(url)}" target="_blank" rel="noopener">${label}${arrow}</a>`;
function header(active='') {
  const links=[['/portfolio/','Trabalhos','work'],['/#services','Serviços','services'],['/sobre/','Sobre','about'],['/#contact','Contato','contact']];
  return `<a class="skip-link" href="#main">Pular para o conteúdo</a><header class="site-header" id="siteHeader"><a class="brand" href="/" aria-label="Take Cut — início"><img src="/logo.png" alt="Take Cut" width="164" height="48" fetchpriority="high"></a><nav class="desktop-nav" aria-label="Navegação principal">${links.map(([href,label,key])=>`<a href="${href}"${key===active?' aria-current="page"':''}>${label}</a>`).join('')}</nav>${external(whatsapp(),'Começar projeto','header-cta')}<button class="menu-toggle" type="button" aria-label="Abrir menu" aria-controls="mobileMenu" aria-expanded="false"><span></span><span></span></button></header><dialog class="mobile-menu" id="mobileMenu" aria-label="Menu principal"><div class="menu-top"><a class="brand" href="/"><img src="/logo.png" alt="Take Cut — início" width="164" height="48"></a><button class="icon-button" type="button" data-close-menu aria-label="Fechar menu">${close}</button></div><nav aria-label="Navegação mobile">${links.map(([href,label],i)=>`<a href="${href}"><span class="mono">0${i+1}</span>${label}${arrow}</a>`).join('')}</nav><div class="menu-bottom">${external(whatsapp(),'Começar um projeto','button button-accent')}<a href="https://www.instagram.com/takecutedit/" target="_blank" rel="noopener">Instagram ↗</a><a href="mailto:takecutedit@gmail.com">takecutedit@gmail.com</a><span class="mono">São Paulo · Brasil / Ideias sem fronteiras</span></div></dialog>`;
}
function footer() {
return `<footer class="site-footer shell"><div class="footer-top"><a href="/" class="footer-brand">TAKE CUT<span>Faça valer o play.</span></a><div><p class="eyebrow">Navegação</p><a href="/portfolio/">Trabalhos</a><a href="/#services">Serviços</a><a href="/sobre/">Sobre</a><a href="/#contact">Contato</a></div><div><p class="eyebrow">Explore</p><a href="/planos/" id="plans">Planos</a><a href="/produtos/">Take Cut Gear</a><a href="/planos/#plan-faq" id="faq">Perguntas frequentes</a><a href="/nichos/" id="nichos">Vídeos para seu negócio</a></div><div><p class="eyebrow">Dê um alô</p><a href="https://www.instagram.com/takecutedit/" target="_blank" rel="noopener">Instagram ↗</a><a href="mailto:takecutedit@gmail.com">E-mail ↗</a><a href="${whatsapp()}" target="_blank" rel="noopener">WhatsApp ↗</a></div></div><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} Take Cut</span><a href="/termos.html">Termos e privacidade</a><button type="button" class="motion-toggle" aria-pressed="false">Pausar animações</button><span class="mono">Feito de ideias. E alguns cortes.</span></div></footer>`;
}
function atmosphere() { return '<div class="stars-bg" id="starsBg" aria-hidden="true"><div class="ufo ufo-one"></div><div class="ufo ufo-two"></div><div class="ufo ufo-three"></div></div><div class="page-transition" aria-hidden="true">CUT<span>.</span></div><span class="custom-cursor" aria-hidden="true">PLAY</span>'; }
function viewer() { return `<dialog class="project-viewer" id="projectViewer" aria-labelledby="viewerTitle"><div class="viewer-top"><span class="mono">TAKE CUT / EM EXIBIÇÃO</span><button type="button" class="icon-button" data-close-viewer aria-label="Fechar vídeo">${close}</button></div><div class="viewer-layout"><div class="viewer-media" id="viewerMedia"></div><div class="viewer-info"><p class="eyebrow" id="viewerCategory"></p><h2 id="viewerTitle"></h2><p id="viewerDescription"></p><div id="viewerTechniques" class="techniques"></div><a id="viewerDetails" class="text-link" href="/portfolio/">Sobre este projeto ${arrow}</a><a id="viewerCta" class="button button-accent" href="${whatsapp()}" target="_blank" rel="noopener">Quero algo assim ${arrow}</a></div></div><div class="viewer-navigation"><button class="icon-button" id="previousProject" aria-label="Projeto anterior">←</button><span id="viewerPosition" class="mono"></span><button class="icon-button" id="nextProject" aria-label="Próximo projeto">→</button></div></dialog>`; }
function workCard(project,{classes='',index='',compact=false,eager=false}={}) {
  const p=project;
  return `<article class="work-card ${escape(p.orientation)} ${classes}" data-project-card="${escape(p.id)}" data-objective="${escape(p.objective.join(' '))}" data-category="${escape(p.category.join('|'))}"><a class="work-link" href="/portfolio/${escape(p.slug)}/" data-project="${escape(p.id)}" aria-label="Assistir: ${escape(p.title)}"><div class="work-media" style="--ratio:${p.width} / ${p.height}" data-preview="${escape(p.previewVideo)}"><img src="${escape(p.thumbnail)}" srcset="${escape(p.thumbnailSmall)} 480w, ${escape(p.thumbnail)} 960w" sizes="${compact?'(max-width: 700px) 78vw, 32vw':'(max-width: 700px) 94vw, 75vw'}" alt="${escape(p.title)}" width="${p.width}" height="${p.height}" loading="${eager?'eager':'lazy'}" decoding="async"><video muted loop playsinline preload="none" aria-hidden="true" tabindex="-1" disablepictureinpicture></video><span class="play-label">${play}<span>Assistir</span></span><span class="media-format mono">${p.orientation==='vertical'?'9:16':p.orientation==='square'?'1:1':'16:9'}</span></div><div class="work-caption"><div><p class="eyebrow">${escape(p.category.slice(0,2).join(' / ') || p.techniques[0])}</p><h3>${escape(p.title)}</h3></div><span class="work-index mono">${index || String(p.order).padStart(2,'0')}${arrow}</span></div></a></article>`;
}
function heading(kicker,title,description='',index='') { return `<div class="section-heading" data-reveal><div><p class="eyebrow">${kicker}</p><h2>${title}</h2></div><div class="section-aside">${description?`<p>${description}</p>`:''}${index?`<span class="mono section-count">${index}</span>`:''}</div></div>`; }
function cta() { return `<section class="final-cta shell" id="contact"><p class="eyebrow" data-reveal>Seu próximo filme começa aqui</p><h2 data-reveal>Tem uma ideia?<br><span>A gente transforma<br>em vídeo.</span></h2>${external(whatsapp(),'Começar um projeto','button button-accent')}<div class="contact-meta"><a href="mailto:takecutedit@gmail.com">takecutedit@gmail.com</a><a href="https://forms.gle/TBiUyHQRnzV3hy9t5" target="_blank" rel="noopener">Prefere enviar um briefing? ↗</a><span>São Paulo / Atendimento em todo o Brasil</span></div></section>`; }
module.exports={escape,arrow,play,close,whatsapp,external,header,footer,atmosphere,viewer,workCard,heading,cta};
